### ISSUE TITLE
Minigame

### ISSUE THREAD

**Issue by sindrsh** [sindrsh/mathworld#11]
Making a minigame for practicing one, and only one, of the following topics:
counting, addition, subtraction, multiplication, division. Must be playable on both PC and tablet.

**Comment by FireSquid6** [comment]
Working on this. Feel free to assign it to me.

**Comment by FireSquid6** [comment]
should we close this?

**Comment by sindrsh** [comment]
It's sort of an ongoing task this one but I'll close it as it is not prioritized right now.
